name: Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.400'
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Initialize Testing Stack
        run: docker-compose up -d
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
